name: Uboot

on:

  workflow_dispatch:
  workflow_call:
#  schedule:
#    - cron: '0 4 * * *' # Scheduled runs every day at 4am UTC

jobs:

  Cancel:
    name: "Cancel currently active"
    if: ${{ github.repository_owner == 'Armbian' }}
    runs-on: qemu
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        if: ${{ github.event.schedule == '' }}
        with:
          all_but_latest: true
          access_token: ${{ secrets.GITHUB_TOKEN }}

  Legacy:

    needs: Cancel
    if: ${{ success() && github.repository_owner == 'Armbian' }}
    uses: ./.github/workflows/include.yml

    with:

      runner: "X64"
      include: 'grep legacy | '

  Current:

    needs: Cancel
    if: ${{ success() && github.repository_owner == 'Armbian' }}
    uses: ./.github/workflows/include.yml

    with:

      runner: "X64"
      include: 'grep current | '

  Edge:
  
    needs: Cancel
    if: ${{ success() && github.repository_owner == 'Armbian' }}
    uses: ./.github/workflows/include.yml

    with:

      runner: "ubuntu-latest"
      include: 'grep edge | '
